_BASE_: ../Base-bagtricks.yml

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

MODEL:
  HEADS:
    EMBEDDING_DIM: 256
  
  LOSSES:
    CE:
      EPSILON: 0.0

SOLVER:
  OPT: SGD
  BASE_LR: 0.01
  ETA_MIN_LR: 7.7e-5

  IMS_PER_BATCH: 64
  MAX_EPOCH: 60
  STEPS: [40, 55]
  WARMUP_ITERS: 1000
  #FREEZE_ITERS: 3000

  CHECKPOINT_PERIOD: 10

#DATALOADER:
#  SAMPLER_TRAIN: TrainingSampler

DATASETS:
  NAMES: ("VeRi", "VeRiX", )
  TESTS: ("VeRi",)

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 256

OUTPUT_DIR: logs/veri/bagtricks_R50-feat256-verix
