_BASE_: ../Base-bagtricks.yml

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]


SOLVER:
  OPT: SGD
  BASE_LR: 0.01
  ETA_MIN_LR: 7.7e-5

  IMS_PER_BATCH: 64
  MAX_EPOCH: 60
  WARMUP_ITERS: 3000
  FREEZE_ITERS: 3000

  CHECKPOINT_PERIOD: 10

DATASETS:
  NAMES: ("VeRi",)
  TESTS: ("VeRi",)

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 256

OUTPUT_DIR: logs/veri/bagtricks_R50
