_BASE_: ../Base-bagtricks.yml

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]
  AUTOAUG:
    ENABLED: True
    PROB: 0.1

MODEL:
  BACKBONE:
    WITH_IBN: True
  HEADS:
    NAME: MultiHead
    EMBEDDING_DIM: 256
    #NECK_FEAT: after
    POOL_LAYER: GeneralizedMeanPoolingP
    #CLS_LAYER: CircleSoftmax
    #SCALE: 64
    #MARGIN: 0.35
  LOSSES:
    NAME: ("CrossEntropyLoss", "SupContrastLoss",)
    CE:
      EPSILON: 0.1
      SCALE: 1.0

    SUPCON:
      SCALE: 1.0



SOLVER:
  OPT: SGD
  BASE_LR: 0.01
  ETA_MIN_LR: 7.7e-5

  IMS_PER_BATCH: 64
  MAX_EPOCH: 60
  WARMUP_ITERS: 3000
  FREEZE_ITERS: 3000

  CHECKPOINT_PERIOD: 10

DATASETS:
  NAMES: ("VeRi",)
  TESTS: ("VeRi",)

DATALOADER:
  NUM_INSTANCE: 16
  SAMPLER_TRAIN: BalancedIdentitySampler

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 256

OUTPUT_DIR: logs/veri/bagtricks_R50-ibn-feat256-multihead-supcon
