_BASE_: ../Base-bagtricks.yml

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

MODEL:
  HEADS:
    EMBEDDING_DIM: 256
  LOSSES:
    TRI:
      HARD_MINING: False
      MARGIN: 0.0

DATASETS:
  NAMES: ("HangzhouPlate", "VeRi", "VehicleID", "VeRiWild",)
  TESTS: ("HangzhouPlate","VeRi","LargeVehicleID", "LargeVeRiWild",)

SOLVER:
  IMS_PER_BATCH: 512 # 512 For 4 GPUs
  MAX_EPOCH: 60
  STEPS: [15, 35, 45]
  WARMUP_ITERS: 3000

  CHECKPOINT_PERIOD: 10

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 128

OUTPUT_DIR: logs/hangzhou_plate/bagtricks_R50_feat256_8gpu_0722
