_BASE_: ../Base-bagtricks.yml

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

MODEL:
  #META_ARCHITECTURE: MALW_Baseline
  BACKBONE:
    #NAME: build_resnet_mixstyle_backbone
    WITH_IBN: True
  HEADS:
    EMBEDDING_DIM: 256
    POOL_LAYER: GeneralizedMeanPoolingP
  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss",)
    CE:
      EPSILON: 0.0
      SCALE: 1.0

    TRI:
      MARGIN: 0.0
      HARD_MINING: True
      NORM_FEAT: False
      SCALE: 1.0

DATASETS:
  NAMES: ("VeRi", "VehicleID", "VeRiWild", "VCA")
  TESTS: ("VeRi",  "LargeVehicleID", "LargeVeRiWild", "VCA")

SOLVER:
  IMS_PER_BATCH: 512 # 512 For 4 GPUs
  MAX_EPOCH: 120
  STEPS: [30, 70, 90]
  WARMUP_ITERS: 5000

  CHECKPOINT_PERIOD: 10

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 256

OUTPUT_DIR: logs/vehicle_combine/bestpractice_R50_feat256_4gpu_combine_vca
